### Переключить активность клиента (включить/выключить)
# Замените {id} на реальный ID клиента
# Если клиент активен - станет неактивным, и наоборот
POST http://localhost:8080/api/clients/1/toggle
Accept: application/json

###
