### Получить QR код для клиента
# Замените {id} на реальный ID клиента
# Откроется HTML страница с QR кодом для сканирования телефоном
GET http://localhost:8080/api/clients/1/qr
Accept: text/html

###
