### Открыть главную страницу с QR кодами
# Каждый запрос генерирует НОВОГО pending клиента
# Клиент будет проверен через 5 минут
# Если подключился - сохранится в БД, если нет - удалится
GET http://localhost:8080/
Accept: text/html
