### Инструкция по настройке Keycloak

# 1. Открыть Keycloak Admin Console: http://localhost:8180
# 2. Войти: admin / admin
# 3. Создать realm: vpn-realm
# 4. Создать роли: user, admin
# 5. Создать client: vpn-mobile (public, для Flutter)
# 6. Создать client: vpn-backend (confidential, для backend)
# 7. Создать тестового пользователя

### Получить токен для тестового пользователя
POST http://localhost:8180/realms/vpn-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=vpn-mobile
&username=test@example.com
&password=test123

### Обновить токен
POST http://localhost:8180/realms/vpn-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id=vpn-mobile
&refresh_token={{refresh_token}}

### Выход (revoke token)
POST http://localhost:8180/realms/vpn-realm/protocol/openid-connect/logout
Content-Type: application/x-www-form-urlencoded

client_id=vpn-mobile
&refresh_token={{refresh_token}}
